# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 070cc95304cbe58b4c6de0789cd3d5bb98d19a45bc149a09133b6dab9533287a0c920b1f31d40a3bf3ab77e516cb0be777c05102c90278b6f0579f947cbc1792

test:
  secret_key_base: febe50073b04ff2d10865ab06076bbc81f92d55594caa5cbb1c2fd9c86a694b41c56893c388a63ec9ec22cbe7454220dd91bb1cb8b3f92abc1a35ec1d6a9bf84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
